apiVersion: v1
kind: Namespace
metadata:
  name: nexus-system
  labels:
    app: nexus-intelligence
    version: "1.0.0"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus-system
data:
  NODE_ENV: "production"
  NEXUS_MODE: "production"
  PORT: "8503"
  HOST: "0.0.0.0"
  DASHBOARD_UPDATE_INTERVAL: "5000"
  ENABLE_LIVE_DATA: "true"
  ENABLE_MOCK_DATA: "true"
  LOG_LEVEL: "INFO"

---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
  namespace: nexus-system
type: Opaque
stringData:
  NEXUS_SECRET_KEY: "CHANGE_THIS_SECURE_NEXUS_SECRET_KEY_IN_PRODUCTION"
  JWT_ALGORITHM: "HS256"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-dashboard
  namespace: nexus-system
  labels:
    app: nexus-dashboard
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus-dashboard
  template:
    metadata:
      labels:
        app: nexus-dashboard
        tier: frontend
    spec:
      containers:
      - name: nexus-dashboard
        image: nexus-intelligence:latest
        ports:
        - containerPort: 8503
          name: http
        envFrom:
        - configMapRef:
            name: nexus-config
        - secretRef:
            name: nexus-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/live-data
            port: 8503
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/live-data
            port: 8503
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-dashboard-service
  namespace: nexus-system
  labels:
    app: nexus-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 8503
    targetPort: 8503
    protocol: TCP
    name: http
  selector:
    app: nexus-dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - nexus.yourdomain.com
    secretName: nexus-tls
  rules:
  - host: nexus.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-dashboard-service
            port:
              number: 8503

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexus-hpa
  namespace: nexus-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexus-dashboard
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80