name: Update README Badge

on:
  push:
    branches: [ main ]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create status badge
      run: |
        echo "Project is active and maintained" > status.txt
    
    - name: Update timestamp
      run: |
        echo "Last updated: $(date)" >> status.txt